---
- name: get latest available build
  uri:
    url: "https://shaman.ceph.com/api/search/?status=ready&project=ceph&flavor=default&distros={{ ansible_facts['distribution'] | lower }}/{{ ansible_facts['distribution_release'] }}/{{ ansible_facts['architecture'] }}&ref={{ ceph_dev_branch }}&sha1={{ ceph_dev_sha1 }}"
    return_content: yes
  run_once: true
  register: latest_build

- name: fetch ceph debian development repository
  uri:
<<<<<<< HEAD
    url: https://shaman.ceph.com/api/repos/ceph/{{ ceph_dev_branch }}/{{ ceph_dev_sha1 }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/repo
=======
    url: "{{ (latest_build.content | from_json)[0]['chacra_url'] }}repo"
>>>>>>> bf8cdad93... Make sure the repo url contains the correct arch
    return_content: yes
  register: ceph_dev_deb_repo

- name: configure ceph debian development repository
  apt_repository:
    repo: "{{ ceph_dev_deb_repo.content }}"
    state: present
    update_cache: yes
